# Practice problem

Problem 1

In [3]:
salaries = [95000, 120000, 105000, 90000, 130000]
average_sal = lambda: sum(salaries)/len(salaries)
print("Avarage = ",average_sal())

Avarage =  108000.0


Problem 2

In [6]:
job_titles = ['Data Scientist', 'Data Engineer', 'Machine Learning Engineer', 'Data Analyst']
data_job = lambda title: "Data" in title
filter_job = filter(data_job,job_titles)
print(list(filter_job))


['Data Scientist', 'Data Engineer', 'Data Analyst']


In [12]:
job_postings = [
    {'title': 'Data Scientist', 'skills': ['Python', 'SQL'], 'remote': True},
    {'title': 'Data Analyst', 'skills': ['Excel', 'SQL'], 'remote': False},
    {'title': 'Machine Learning Engineer', 'skills': ['Python', 'TensorFlow'], 'remote': True},
    {'title': 'Software Developer', 'skills': ['Java', 'C++'], 'remote': True}
]

remote_job = lambda job : job["remote"]
filter_job = filter(remote_job,job_postings)
print(list(filter_job))

[{'title': 'Data Scientist', 'skills': ['Python', 'SQL'], 'remote': True}, {'title': 'Machine Learning Engineer', 'skills': ['Python', 'TensorFlow'], 'remote': True}, {'title': 'Software Developer', 'skills': ['Java', 'C++'], 'remote': True}]


In [2]:
import numpy as np
years = np.array([1,2,3,4,5])

yearadd = years+1
yearadd

# yearsub = years-1
# yearsub

# yearmul = years*1
# yearmul

# yeardiv = years/1
# yeardiv

# #Silicing in numpy array

# years[1:3]

# #boolean indexing
# condition_year = years [years > 2]
# condition_year




array([2, 3, 4, 5, 6])

In [12]:
n = [10,20,30]
n3 = np.sum(n)
print(n3)

n4 = np.prod(n)
print(n4)

n5 = np.cumsum(n)
print(n5)

n6 = np.cumprod(n)
print(n6)

60
6000
[10 30 60]
[  10  200 6000]


**NUMpy nan function**

In [15]:
import numpy as n
arr1 = n.array([1,2,3,4,5,6,7,8])
print(arr1)

# testing nan

arr2 = n.array([1,2,3,4,5,n.nan,7,n.nan])
sum = n.nansum(arr2)
print(type(n.nan))
print(sum)

print(n.nanmean(arr2))
print(n.nanmedian(arr2))


[1 2 3 4 5 6 7 8]
<class 'float'>
22.0
3.6666666666666665
3.5
